server:
  port: 8080

spring:
  application:
    name: spring-boot-quick-start
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_quick_start?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # HikariCP连接池配置
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 连接测试查询
      connection-test-query: SELECT 1
      # 空闲连接最大存活时间（毫秒）
      idle-timeout: 600000
      # 连接最大存活时间（毫秒）
      max-lifetime: 1800000
      # 连接池名称
      pool-name: HikariCP
  
  # JPA配置
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # 连接池配置
        connection:
          provider_disables_autocommit: true
        # 批量操作配置
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        # 查询配置
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
        # 统计配置
        generate_statistics: false
        # 会话配置
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
